port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  fake-ip-filter:
  - "+.*"
  nameserver:
    - 8.8.8.8
    - 1.1.1.1
  fallback:
    - https://dns.google/dns-query #UMUM
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
  proxy-server-nameserver:
    - 104.22.4.240 #IP VIDIO
    - 104.22.5.240 #IP VIDIO
    - 112.215.198.248 #DNS XL
    - 112.215.198.254 #DNS XL
proxies:
  - name: rush55
    server: ava.game.naver.com
    port: 443
    type: vless
    uuid: 9df07563-9088-44ec-b3f7-a5b55f6773a1
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sg-do5.esge.web.id
    network: ws
    ws-opts:
      path: /vless
      headers:
        Host: sg-do5.esge.web.id
    udp: true
    
  - name: rushhh
    server: ava.game.naver.com
    port: 443
    type: vmess
    uuid: a1b493c5-ccba-4751-9206-fb0fb03122bd
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id-biznet.rmatstore.cloud
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: id-biznet.rmatstore.cloud
    udp: true
    
proxy-groups:
  - name: ID-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies: 
      - rushhh
      - rush55

  - name: MIX-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - rush55
      - rushhh
      
  - name: IKLAN
    type: select
    proxies:
     - MIX-X
     - REJECT

  - name: GAME
    type: select
    proxies:
     - ID-X
     - DIRECT
     - REJECT

rules:
 - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
 - RULE-SET,Block,IKLAN
 - RULE-SET,Game,GAME
 - RULE-SET,Umum,MIX-X
 - RULE-SET,indo,ID-X
 - RULE-SET,Sosmed,MIX-X
 - RULE-SET,Streaming,MIX-X
 - RULE-SET,Bankid,ID-X
 - RULE-SET,Tiktok,MIX-X
 - RULE-SET,Meta,MIX-X
 - RULE-SET,PortGame,GAME
 - MATCH,MIX-X


rule-providers:
  Game:
    type: file
    behavior: classical
    path: ./game.yaml 
  PortGame:
    type: file
    behavior: classical
    path: ./portgame.yaml
  Umum:
    type: file
    behavior: classical
    path: ./umum.yaml 
  indo:
    type: file
    behavior: classical
    path: ./indo.yaml
  Sosmed:
    type: file
    behavior: classical
    path: ./sosmed.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./streaming.yaml
  Bankid:
    type: file
    behavior: domain
    path: ./bankid.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./meta.yaml
  Block:
    type: file
    behavior: domain
    path: ./block.yaml  
